name: pluto_settings
description: Flutter facade for Pluto settings services.
version: 0.1.0
environment:
  sdk: ^3.12.0
resolution: workspace
dependencies:
  flutter:
    sdk: flutter
  meta: ^1.17.0
  pluto_core: ^0.1.0
dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
