FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
      binutils \
      ca-certificates \
      curl \
      file \
      git \
      lsb-release \
      ninja-build \
      pkg-config \
      python-is-python3 \
      python3 \
      unzip \
      xz-utils \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /build/flutter/engine/src
