#ifndef PLUTO_PRESENTER_NATIVE_RM2_RM2_SCAN_ENCODER_H_
#define PLUTO_PRESENTER_NATIVE_RM2_RM2_SCAN_ENCODER_H_

#include <chrono>
#include <cstddef>
#include <cstdint>
#include <functional>
#include <memory>
#include <span>

namespace pluto::native::rm2 {

inline constexpr std::size_t kRm2PanelWidth = 1404;
inline constexpr std::size_t kRm2PanelHeight = 1872;
inline constexpr std::size_t kRm2ScanoutWidth = 260;
inline constexpr std::size_t kRm2ScanoutHeight = 1408;
inline constexpr std::size_t kRm2ScanoutStrideBytes = 1040;
inline constexpr std::size_t kRm2SlotBytes =
    kRm2ScanoutHeight * kRm2ScanoutStrideBytes;
inline constexpr std::size_t kRm2ActiveSlots = 16;
inline constexpr std::size_t kRm2IdleSlot = 16;
inline constexpr std::size_t kRm2MappedSlots = 17;

struct Rm2PanelRect {
  std::uint16_t row_min = 0;
  std::uint16_t row_max = 0;
  std::uint16_t column_min = 0;
  std::uint16_t column_max = 0;

  std::size_t row_count() const {
    return static_cast<std::size_t>(row_max - row_min) + 1;
  }
  std::size_t column_count() const {
    return static_cast<std::size_t>(column_max - column_min) + 1;
  }
};

struct Rm2PhaseRegion {
  Rm2PanelRect rect;
  std::size_t transition_offset = 0;
};

// Builds the immutable high-half control template and a selected uniform
// low-half drive pattern. The exact 260x1408 layout is profile-gated by the
// device backend before any generated byte reaches scanout.
bool fill_rm2_scan_slot(std::span<std::byte> slot, std::uint16_t drive_pattern);

// Verifies the complete immutable control template and a zero-drive HOLD in
// every low half. Warm handoff uses this against the live idle scan page; a
// zero-filled or partially cleared mapping is not an equivalent safe page.
bool rm2_scan_slot_is_safe_hold(std::span<const std::byte> slot);

// Owns the RM2 full-panel helper for the lifetime of one display backend.
// Reusing the pre-affined helper removes thread creation from every 11.763 ms
// scan phase while keeping the pure encode_rm2_phase helper deterministic for
// host/reference tests.
class Rm2PhaseEncoder final {
public:
  Rm2PhaseEncoder();
  ~Rm2PhaseEncoder();

  Rm2PhaseEncoder(const Rm2PhaseEncoder &) = delete;
  Rm2PhaseEncoder &operator=(const Rm2PhaseEncoder &) = delete;

  bool ready() const noexcept;
  bool encode(std::span<std::byte> slot, const Rm2PanelRect &rect,
              std::span<const std::uint8_t> transition_keys,
              std::span<const std::uint8_t> phase_lut);

  // Encodes all disjoint damage regions with one phase-LUT expansion. Large
  // regions use both exact RM2 cores; sparse regions avoid per-region LUT
  // rebuilds and retain their independent scan-cell bounds.
  bool encode_regions(std::span<std::byte> slot,
                      std::span<const Rm2PhaseRegion> regions,
                      std::span<const std::uint8_t> transition_keys,
                      std::span<const std::uint8_t> phase_lut);

  // Returns CPU time consumed by the persistent helper thread. This is a
  // read-only diagnostic used by the RM2 hardware benchmark to distinguish
  // useful encoding from caller and wait-strategy CPU. Unsupported hosts
  // report zero.
  std::chrono::nanoseconds worker_cpu_time() noexcept;

private:
  class Impl;
  std::unique_ptr<Impl> impl_;
};

struct Rm2PanResult {
  bool operation_ok = false;
  std::chrono::nanoseconds duration{};
  // Captured next to the ioctl return, before worker notification latency.
  std::chrono::steady_clock::time_point completed_at{};
};

// Runs the RM2's blocking FBIOPAN_DISPLAY operation on a persistent worker so
// the presenter thread and its phase helper can prepare the next free slot
// during the current physical scan. begin() does not return until the worker
// has accepted the slot and is entering the blocking operation; finish()
// prevents slot reuse until that operation completes. Together they form a
// strict one-entry rendezvous without exposing a queue-dispatch gap to the
// physical scan cadence.
class Rm2PanWorker final {
public:
  using PanCallback =
      std::function<bool(std::uint32_t slot, Rm2PanResult *out_result)>;

  explicit Rm2PanWorker(PanCallback callback);
  ~Rm2PanWorker();

  Rm2PanWorker(const Rm2PanWorker &) = delete;
  Rm2PanWorker &operator=(const Rm2PanWorker &) = delete;

  bool ready() const noexcept;
  bool begin(std::uint32_t slot);
  bool finish(Rm2PanResult *out_result);

  // Returns CPU time consumed by the blocking-pan worker. Unsupported hosts
  // report zero.
  std::chrono::nanoseconds worker_cpu_time() noexcept;

private:
  class Impl;
  std::unique_ptr<Impl> impl_;
};

// Encodes one phase into an already initialized slot. transition_keys is
// column-major over rect; each byte is new_gray4<<4 | old_gray4. phase_lut is
// the pre-expanded 16x16 table for exactly this phase. The split keeps WBF
// parsing and record lookup entirely out of the panel-frame hot loop.
bool encode_rm2_phase(std::span<std::byte> slot, const Rm2PanelRect &rect,
                      std::span<const std::uint8_t> transition_keys,
                      std::span<const std::uint8_t> phase_lut);

// Restores only the low halves touched by encode_rm2_phase. The static
// control template in each high half remains intact.
bool clear_rm2_phase_cells(std::span<std::byte> slot, const Rm2PanelRect &rect);

inline std::uint8_t rgb565_to_rm2_level(std::uint16_t pixel) {
  const std::uint32_t red5 = (pixel >> 11U) & 0x1fU;
  const std::uint32_t green6 = (pixel >> 5U) & 0x3fU;
  const std::uint32_t blue5 = pixel & 0x1fU;
  const std::uint32_t red8 = (red5 << 3U) | (red5 >> 2U);
  const std::uint32_t green8 = (green6 << 2U) | (green6 >> 4U);
  const std::uint32_t blue8 = (blue5 << 3U) | (blue5 >> 2U);
  const std::uint32_t luma =
      (77U * red8 + 150U * green8 + 29U * blue8 + 128U) >> 8U;
  return static_cast<std::uint8_t>((luma * 15U + 127U) / 255U);
}

// The RM2 Fast class is backed by waveform mode 6 (AF/A2). It must only be
// credited with the binary physical endpoints that waveform can settle.
inline std::uint8_t rm2_fast_level(std::uint8_t gray4) {
  return gray4 >= 8U ? 15U : 0U;
}

} // namespace pluto::native::rm2

#endif // PLUTO_PRESENTER_NATIVE_RM2_RM2_SCAN_ENCODER_H_
