#ifndef PLUTO_PRESENTER_NATIVE_RM2_RM2_SCAN_ENCODER_H_
#define PLUTO_PRESENTER_NATIVE_RM2_RM2_SCAN_ENCODER_H_

#include <cstddef>
#include <cstdint>
#include <span>

#include "generated/rm2_rgb565_lut.h"

namespace pluto::native::rm2 {

inline constexpr std::size_t kRm2PanelWidth = 1404;
inline constexpr std::size_t kRm2PanelHeight = 1872;
inline constexpr std::size_t kRm2ScanoutWidth = 260;
inline constexpr std::size_t kRm2ScanoutHeight = 1408;
inline constexpr std::size_t kRm2ScanoutStrideBytes = 1040;
inline constexpr std::size_t kRm2SlotBytes =
    kRm2ScanoutHeight * kRm2ScanoutStrideBytes;
inline constexpr std::size_t kRm2ActiveSlots = 16;
inline constexpr std::size_t kRm2IdleSlot = 16;
inline constexpr std::size_t kRm2MappedSlots = 17;

struct Rm2PanelRect {
  std::uint16_t row_min = 0;
  std::uint16_t row_max = 0;
  std::uint16_t column_min = 0;
  std::uint16_t column_max = 0;

  std::size_t row_count() const {
    return static_cast<std::size_t>(row_max - row_min) + 1;
  }
  std::size_t column_count() const {
    return static_cast<std::size_t>(column_max - column_min) + 1;
  }
};

// Builds the immutable high-half control template and a selected uniform
// low-half drive pattern. The exact 260x1408 layout is profile-gated by the
// device backend before any generated byte reaches scanout.
bool fill_rm2_scan_slot(std::span<std::byte> slot, std::uint16_t drive_pattern);

// Verifies the complete immutable control template and a zero-drive HOLD in
// every low half. Warm handoff uses this against the live idle scan page; a
// zero-filled or partially cleared mapping is not an equivalent safe page.
bool rm2_scan_slot_is_safe_hold(std::span<const std::byte> slot);

// Encodes one phase into an already initialized slot. transition_keys is
// column-major over rect; each byte is new_gray4<<4 | old_gray4. phase_lut is
// the pre-expanded 16x16 table for exactly this phase. The split keeps WBF
// parsing and record lookup entirely out of the panel-frame hot loop.
bool encode_rm2_phase(std::span<std::byte> slot, const Rm2PanelRect &rect,
                      std::span<const std::uint8_t> transition_keys,
                      std::span<const std::uint8_t> phase_lut);

// Restores only the low halves touched by encode_rm2_phase. The static
// control template in each high half remains intact.
bool clear_rm2_phase_cells(std::span<std::byte> slot, const Rm2PanelRect &rect);

inline std::uint8_t rgb565_to_rm2_level(std::uint16_t pixel) {
  return kRm2Rgb565LevelLut[pixel];
}

// The RM2 Fast class is backed by waveform mode 6 (AF/A2). It must only be
// credited with the binary physical endpoints that waveform can settle.
inline std::uint8_t rm2_fast_level(std::uint8_t gray4) {
  return gray4 >= 8U ? 15U : 0U;
}

} // namespace pluto::native::rm2

#endif // PLUTO_PRESENTER_NATIVE_RM2_RM2_SCAN_ENCODER_H_
