#include <cstddef>
#include <cstdint>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <limits>
#include <span>
#include <string>
#include <string_view>
#include <system_error>
#include <vector>

#include "presenter/native/rm2/wbf_decoder.h"

namespace {

using pluto::native::rm2::WbfMetadata;

enum class OutputFormat { kJson, kCpp };

void usage() {
  std::cerr << "usage: pluto_wbf_inspect [--format=json|cpp] "
               "[--expect-sha256=<64 lowercase hex>] <file.wbf>\n";
}

bool valid_digest(std::string_view digest) {
  if (digest.size() != 64) {
    return false;
  }
  for (const char value : digest) {
    if (!((value >= '0' && value <= '9') || (value >= 'a' && value <= 'f'))) {
      return false;
    }
  }
  return true;
}

void emit_json_array(const std::vector<std::uint8_t> &values) {
  std::cout << '[';
  for (std::size_t index = 0; index < values.size(); ++index) {
    if (index != 0) {
      std::cout << ',';
    }
    std::cout << static_cast<unsigned>(values[index]);
  }
  std::cout << ']';
}

void emit_json_array(const std::vector<std::uint16_t> &values) {
  std::cout << '[';
  for (std::size_t index = 0; index < values.size(); ++index) {
    if (index != 0) {
      std::cout << ',';
    }
    std::cout << values[index];
  }
  std::cout << ']';
}

void emit_json(const WbfMetadata &metadata) {
  std::cout << "{\n"
            << "  \"sha256\": \""
            << pluto::native::rm2::wbf_sha256_hex(metadata.source_sha256)
            << "\",\n"
            << "  \"crc32\": \"" << std::hex << std::setfill('0')
            << std::setw(8) << metadata.file_crc32 << std::dec << "\",\n"
            << "  \"fileSize\": " << metadata.file_size << ",\n"
            << "  \"serial\": " << metadata.serial << ",\n"
            << "  \"waveformName\": \"" << metadata.waveform_name << "\",\n"
            << "  \"panelSignature\": \"" << metadata.panel_signature << "\",\n"
            << "  \"fplLot\": " << metadata.fpl_lot << ",\n"
            << "  \"modeVersion\": "
            << static_cast<unsigned>(metadata.mode_version) << ",\n"
            << "  \"waveformVersion\": "
            << static_cast<unsigned>(metadata.waveform_version) << ",\n"
            << "  \"waveformSubversion\": "
            << static_cast<unsigned>(metadata.waveform_subversion) << ",\n"
            << "  \"frameRateHz\": "
            << static_cast<unsigned>(metadata.frame_rate_hz) << ",\n"
            << "  \"modeCount\": " << static_cast<unsigned>(metadata.mode_count)
            << ",\n"
            << "  \"temperatureCount\": "
            << static_cast<unsigned>(metadata.temperature_count) << ",\n"
            << "  \"temperatureBoundariesCelsius\": ";
  emit_json_array(metadata.temperature_boundaries_celsius);
  std::cout << ",\n  \"phaseCounts\": ";
  emit_json_array(metadata.phase_counts);
  std::cout << ",\n  \"uniqueRecordCount\": " << metadata.unique_record_count
            << ",\n  \"decodedPackedBytes\": " << metadata.decoded_packed_bytes
            << "\n}\n";
}

template <typename T>
void emit_cpp_array(std::string_view name, const std::vector<T> &values,
                    std::string_view type) {
  std::cout << "inline constexpr std::array<" << type << ", " << values.size()
            << "> " << name << " = {";
  for (std::size_t index = 0; index < values.size(); ++index) {
    if (index != 0) {
      std::cout << ',';
    }
    std::cout << static_cast<unsigned>(values[index]);
  }
  std::cout << "};\n";
}

void emit_cpp(const WbfMetadata &metadata) {
  std::cout
      << "// Generated by pluto_wbf_inspect. Metadata only; no vendor LUT "
         "bytes.\n"
      << "#pragma once\n\n"
      << "#include <array>\n#include <cstddef>\n#include <cstdint>\n\n"
      << "namespace pluto::generated::rm2_wbf {\n"
      << "inline constexpr char kSha256[] = \""
      << pluto::native::rm2::wbf_sha256_hex(metadata.source_sha256) << "\";\n"
      << "inline constexpr char kPanelSignature[] = \""
      << metadata.panel_signature << "\";\n"
      << "inline constexpr std::uint32_t kFileSize = " << metadata.file_size
      << "u;\n"
      << "inline constexpr std::uint32_t kFileCrc32 = 0x" << std::hex
      << std::setfill('0') << std::setw(8) << metadata.file_crc32 << std::dec
      << "u;\n"
      << "inline constexpr std::uint16_t kFplLot = " << metadata.fpl_lot
      << "u;\n"
      << "inline constexpr std::uint8_t kModeVersion = "
      << static_cast<unsigned>(metadata.mode_version) << "u;\n"
      << "inline constexpr std::size_t kModeCount = "
      << static_cast<unsigned>(metadata.mode_count) << "u;\n"
      << "inline constexpr std::size_t kTemperatureCount = "
      << static_cast<unsigned>(metadata.temperature_count) << "u;\n";
  emit_cpp_array("kTemperatureBoundariesCelsius",
                 metadata.temperature_boundaries_celsius, "std::uint8_t");
  emit_cpp_array("kPhaseCounts", metadata.phase_counts, "std::uint16_t");
  std::cout << "}  // namespace pluto::generated::rm2_wbf\n";
}

} // namespace

int main(int argc, char **argv) {
  OutputFormat format = OutputFormat::kJson;
  std::string expected_sha256;
  std::string path;
  for (int index = 1; index < argc; ++index) {
    const std::string_view argument(argv[index]);
    if (argument == "--format=json") {
      format = OutputFormat::kJson;
    } else if (argument == "--format=cpp") {
      format = OutputFormat::kCpp;
    } else if (argument.starts_with("--expect-sha256=")) {
      expected_sha256 = argument.substr(16);
      if (!valid_digest(expected_sha256)) {
        usage();
        return 64;
      }
    } else if (!argument.empty() && argument.front() == '-') {
      usage();
      return 64;
    } else if (path.empty()) {
      path = argument;
    } else {
      usage();
      return 64;
    }
  }
  if (path.empty()) {
    usage();
    return 64;
  }

  std::error_code filesystem_error;
  const std::uintmax_t size =
      std::filesystem::file_size(path, filesystem_error);
  if (filesystem_error) {
    std::cerr << "wbf inspect: " << filesystem_error.message() << '\n';
    return 66;
  }
  if (size > pluto::native::rm2::kMaxWbfFileBytes) {
    std::cerr << "wbf inspect: input exceeds bounded file limit\n";
    return 65;
  }
  std::ifstream input(path, std::ios::binary);
  if (!input) {
    std::cerr << "wbf inspect: unable to open input\n";
    return 66;
  }
  if (size > static_cast<std::uintmax_t>(
                 std::numeric_limits<std::streamsize>::max())) {
    std::cerr
        << "wbf inspect: input cannot be represented by the host stream\n";
    return 65;
  }
  std::vector<std::uint8_t> bytes(static_cast<std::size_t>(size));
  if (!bytes.empty()) {
    input.read(reinterpret_cast<char *>(bytes.data()),
               static_cast<std::streamsize>(bytes.size()));
  }
  if (input.gcount() != static_cast<std::streamsize>(bytes.size()) ||
      input.bad()) {
    std::cerr << "wbf inspect: input changed or could not be read completely\n";
    return 66;
  }
  char trailing = 0;
  if (input.get(trailing)) {
    std::cerr << "wbf inspect: input changed while it was being read\n";
    return 66;
  }
  WbfMetadata metadata;
  std::string error;
  if (!pluto::native::rm2::WbfDecoder::inspect(bytes, &metadata, &error)) {
    std::cerr << "wbf inspect: " << error << '\n';
    return 65;
  }
  const std::string actual_sha256 =
      pluto::native::rm2::wbf_sha256_hex(metadata.source_sha256);
  if (!expected_sha256.empty() && actual_sha256 != expected_sha256) {
    std::cerr << "wbf inspect: SHA-256 does not match --expect-sha256\n";
    return 65;
  }

  if (format == OutputFormat::kCpp) {
    emit_cpp(metadata);
  } else {
    emit_json(metadata);
  }
  return 0;
}
